import "./globals.css";
import Link from "next/link";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-gray-50 text-gray-900">
        <div className="max-w-[1580px] mx-auto px-4 md:px-0">
          <header className="flex items-center justify-between p-6">
            <div className="flex items-center space-x-3">
              <div className="h-10 w-10 rounded-lg bg-indigo-600 flex items-center justify-center text-white font-bold">
                CR
              </div>
              <div>
                <h1 className="text-lg font-semibold">Credit Rule Engine</h1>
                <p className="text-sm text-gray-500">Admin UI</p>
              </div>
            </div>
            <nav className="flex items-center space-x-4">
              <Link
                href="/"
                className="text-sm font-medium text-gray-700 hover:text-indigo-600">
                Home
              </Link>
              <Link
                href="/facts"
                className="text-sm font-medium text-gray-700 hover:text-indigo-600">
                Facts
              </Link>
              <Link
                href="/rules"
                className="text-sm font-medium text-gray-700 hover:text-indigo-600">
                Rules
              </Link>
              <Link
                href="/outcomes"
                className="text-sm font-medium text-gray-700 hover:text-indigo-600">
                Outcomes
              </Link>
              <Link
                href="/builder"
                className="text-sm font-medium text-gray-700 hover:text-indigo-600">
                Builder
              </Link>
              <Link
                href="/test-cases"
                className="text-sm font-medium text-gray-700 hover:text-indigo-600">
                Test Cases
              </Link>
            </nav>
          </header>

          <main className="px-6 pb-4">{children}</main>
        </div>
      </body>
      <ToastContainer />
    </html>
  );
}
